name: Deploy WAR to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven
      run: sudo apt-get install maven -y

    - name: Build WAR file
      run: mvn clean package

    - name: Upload project to server
      uses: appleboy/scp-action@master
      with:
        host: 103.91.187.228
        username: root
        port: 2244
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/opt/apps/springboot-app"

    - name: SSH and deploy container
      uses: appleboy/ssh-action@master
      with:
        host: 103.91.187.228
        username: root
        port: 2244
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/apps/springboot-app
          docker stop springboot-war || true
          docker rm springboot-war || true
          docker rmi springboot-war-app || true
          docker build -t springboot-war-app .
          docker run -d -p 8084:8084 --name springboot-war springboot-war-app
