name: Deploy WAR Spring Boot Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2244
        script: |
          echo "Deploying WAR Spring Boot app via Docker..."
          cd /opt/apps/springboot-app

          echo "Giving execute permission to Maven wrapper..."
          chmod +x mvnw

          echo "Building WAR file..."
          ./mvnw clean package -DskipTests

          echo "Building Docker image locally..."
          docker build -t springboot-war-app .

          echo "Stopping old container if exists..."
          docker stop springboot-war || true
          docker rm springboot-war || true

          echo "Running WAR file in Tomcat container..."
          docker run -d --name springboot-war -p 8080:8080 springboot-war-app

