name: Deploy Spring Boot App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2244                    
        script: |
          echo "Deploying Spring Boot app via Docker..."
          cd /opt/apps/springboot-app

          echo "Building Docker image..."
          docker build -t springboot-app .

          echo "Stopping and removing old container if it exists..."
          docker stop springboot || true
          docker rm springboot || true

          echo "Running new container..."
          docker run -d --name springboot -p 8080:8080 springboot-app
