name: Deploy WAR Spring Boot Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2244
        source: "."
        target: "/opt/apps/springboot-app"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2244
        script: |
          echo "Deploying WAR Spring Boot app via Docker..."
          cd /opt/apps/springboot-app

          echo "Building WAR..."
          ./mvnw clean package -DskipTests

          echo "Building Docker image with WAR..."
          docker build -t springboot-war-app .

          echo "Stopping and removing old container..."
          docker stop springboot || true
          docker rm springboot || true

          echo "Running new container..."
          docker run -d --name springboot -p 8080:8080 springboot-war-app
